vpc_id: vpc-31721b59
keypair: maishsk-keypair
vpc_cidr_block: 192.168.100.0/24
region: us-east-2
virtual_ip: 172.16.1.100
instance_count: 2
instance_type: t2.large
use_public_ip: "no"
network_to_use: "internal"
master_slave: "true"
source_dest_check_enabled: "no"
iam_role: vrrp_Role
volume_type: gp2
root_disk_size: 50
component_name: haproxy
image_id: ami-0b59bfac6be064b78
# IAM policy for vrrp
trust_policy:
  Version: '2012-10-17'
  Statement:
  - Action:
    - ec2:CreateRoute
    - ec2:ReplaceRoute
    Effect: Allow
    Resource: "*"
#### Security group rules for the component
component_rules:
  - proto: tcp
    from_port: 1
    to_port: 65535
    cidr_ip: "{{ vpc_cidr_block }}"
