---
- name: Create the IAM role
  iam:
    iam_type: role
    name: "{{ iam_role }}"
    state: present
    trust_policy: "{{ trust_policy }}"
      Version: '2012-10-17'
      Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: ec2.amazonaws.com

- name: Assign a policy to role
  iam_policy:
    iam_type: role
    iam_name: "{{ iam_role }}"
    policy_name: "{{ iam_role }}_policy"
    state: present
    policy_document: "{{ policy_file }}"
