---
- name: Create IAM Managed Policy
  iam_managed_policy:
    policy_name: "{{ iam_role }}_policy"
    policy_description: "{{ policyDescription }}"
    policy: "{{ lookup('file', '{{ policy_file }}') }}"
    state: present
  register: iam_policy

- name: Create a role and attach a managed policy
  iam_role:
    name: "{{ iam_role }}"
    assume_role_policy_document: "{{ lookup('file','trust_policy.json') }}"
    managed_policy: "{{ iam_policy.policy.arn }}"
    description: "{{ role_description }}"
