---
- name: Create the IAM role
  iam:
    iam_type: role
    name: "{{ iam_role }}"
    state: present
    trust_policy: "{{ trust_policy }}"

- name: Create IAM Managed Policy
  iam_managed_policy:
    policy_name: "{{ iam_role }}_policy"
    policy_description: "Policy to allow HAproxy to manage routes for high availability"
    policy: "{{ lookup('file', '{{ policy_file }}') }}"
    state: present
  register: iam_policy
  
# - name: Assign a policy to role
#   iam_policy:
#     iam_type: role
#     iam_name: "{{ iam_role }}"
#     policy_name: "{{ iam_role }}_policy"
#     state: present
#     policy_document: "{{ policy_file }}"
